[pytest]
addopts = -v --html=reports/reporte.html --self-contained-html
log_file = reports/ejecucion.log
log_file_level = INFO
log_file_format = %(asctime)s [%(levelname)s] %(name)s: %(message)s
log_cli = false
